CREATE TABLE `skills` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `skill` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `status` enum('1','0') COLLATE utf8_unicode_ci NOT NULL DEFAULT '1',
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `skills` (`skill`) VALUES 
('ActionScript'),
('Ajax'),
('AngularJS'),
('AppleScript'),
('Asp'),
('Basic'),
('Bootstrap'),
('C'),
('C++'),
('Clojure'),
('Cobol'),
('ColdFusion'),
('Composer'),
('CSS'),
('Emmet'),
('Erlang'),
('Fortran'),
('Git'),
('Groovy'),
('Haskell'),
('HTML'),
('Java'),
('JavaScript'),
('jQuery'),
('Laravel'),
('Lisp'),
('Mercurial'),
('MSSQL'),
('MySQL'),
('NodeJs'),
('Oracle'),
('Perl'),
('PHP'),
('Python'),
('RegEx'),
('Ruby'),
('Sass'),
('Scala'),
('Sheme'),
('SQL'),
('Symphony'),
('Vagrant'),
('Web Development'),
('Yii');
